### ISSUE TITLE
Align data validation on latest reference values

### ISSUE THREAD

**Issue by demeringo** [Boavizta/ict-sustainability-tools#63]
## Bug description

The rules of data validation of reference values are not aligned on actual reference values used in the CSV.

## To Reproduce

Try to validate data locally

```
pip install frictionless 
cd ictst/data
# validate that format of fields matches description
frictionless validate tools.resources.yaml
```

Data validation fails

It returns
```sh
─────────────────────────────────────────────────────────────────── Dataset ────────────────────────────────────────────────────────────────────
                dataset
┏━━━━━━━┳━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━┓
┃ name  ┃ type  ┃ path      ┃ status  ┃
┡━━━━━━━╇━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━┩
│ tools │ table │ tools.csv │ INVALID │
└───────┴───────┴───────────┴─────────┘
──────────────────────────────────────────────────────────────────── Tables ────────────────────────────────────────────────────────────────────
                                                                     tools
┏━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Row ┃ Field ┃ Type             ┃ Message                                                                                                     ┃
┡━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 14  │ 8     │ constraint-error │ The cell "Infra - Cloud" in row at position "14" and field "main_perimeter" at position "8" does not        │
│     │       │                  │ conform to a constraint: constraint "enum" is "['Global | Information System', 'Global | Digital            │
│     │       │                  │ Advertising', 'Infra | Datacenter', 'Infra | Cloud', 'Infra | Network', 'Equipment | End-user Devices',     │
│     │       │                  │ 'Equipment | IoT', 'Equipment | Industrial equipment', 'Software | Development tools', 'Software | CI/CD',  │
│     │       │                  │ 'Software | Backend', 'Software | API', 'Software | Mobile Apps', 'Software | Web Apps', 'Software | Web    │
│     │       │                  │ Content', 'Global | Digital Workspace', 'To Be Qualified']"                                                 │
│ 42  │ 8     │ constraint-error │ The cell "Software - Web Apps" in row at position "42" and field "main_perimeter" at position "8" does not  │
│     │       │                  │ conform to a constraint: constraint "enum" is "['Global | Information System', 'Global | Digital            │
│     │       │                  │ Advertising', 'Infra | Datacenter', 'Infra | Cloud', 'Infra | Network', 'Equipment | End-user Devices',     │
│     │       │                  │ 'Equipment | IoT', 'Equipment | Industrial equipment', 'Software | Development tools', 'Software | CI/CD',  │
│     │       │                  │ 'Software | Backend', 'Software | API', 'Software | Mobile Apps', 'Software | Web Apps', 'Software | Web    │
│     │       │                  │ Content', 'Global | Digital Workspace', 'To Be Qualified']"                                                 │
│ 43  │ 8     │ constraint-error │ The cell "Software - Web Apps" in row at position "43" and field "main_perimeter" at position "8" does not  │
│     │       │                  │ conform to a constraint: constraint "enum" is "['Global | Information System', 'Global | Digital            │
│     │       │                  │ Advertising', 'Infra | Datacenter', 'Infra | Cloud', 'Infra | Network', 'Equipment | End-user Devices',     │
│     │       │                  │ 'Equipment | IoT', 'Equipment | Industrial equipment', 'Software | Development tools', 'Software | CI/CD',  │
│     │       │                  │ 'Software | Backend', 'Software | API', 'Software | Mobile Apps', 'Software | Web Apps', 'Software | Web    │
│     │       │                  │ Content', 'Global | Digital Workspace', 'To Be Qualified']"                                                 │
│ 71  │ 8     │ constraint-error │ The cell "Equipment - End-user Devices" in row at position "71" and field "main_perimeter" at position "8"  │
│     │       │                  │ does not conform to a constraint: constraint "enum" is "['Global | Information System', 'Global | Digital   │
│     │       │                  │ Advertising', 'Infra | Datacenter', 'Infra | Cloud', 'Infra | Network', 'Equipment | End-user Devices',     │
│     │       │                  │ 'Equipment | IoT', 'Equipment | Industrial equipment', 'Software | Development tools', 'Software | CI/CD',  │
│     │       │                  │ 'Software | Backend', 'Software | API', 'Software | Mobile Apps', 'Software | Web Apps', 'Software | Web    │
│     │       │                  │ Content', 'Global | Digital Workspace', 'To Be Qualified']"                                                 │
└─────┴───────┴──────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

For example the `main_permiter` expect the values to be in the form of `Global | Information System` while the CSV contains `Global - Information System`

See https://github.com/Boavizta/ict-sustainability-tools/blob/f979108064818ee980a5251e39b96cf34ec4e59b/ictst/data/tools.resources.yaml#L31

```
- name: main_perimeter
      type: string
      constraints:
        enum:
        - Global | Information System
        - Global | Digital Advertising
        - Infra | Datacenter
```

It will make the data validation fails and likely introduce some problems in display (see also the schema)

## Expected behavior

Align the definition file on the content of the CSV

**Comment by demeringo** [comment]
Very few constraints are implemented for now, we may need extra like

```yml
- name: licence
      type: string
      constraints:
        enum:
        - Open-Source under Apache 2.0 licence
        - Open-Source under AGPLv3 licence
        - Open-Source under GPLv2 licence
        - Open-Source under GPLv3 licence
        - Open-Source under BSD-3 licence
        - Open-Source under MIT license
        - Creative Commons (CC-BY-NC-ND)
        - Creative Commons (CC-BY)
        - Open-Source under an unknown licence
        - Business Source - non permissive licence
        - Closed Source / Commercial
```
